development:
  stripe_secret_key: 'sk_test_51K94u5GTOwaKvPHXmQZk5UIuV5Ye9dYwWQymazbCvB29G7nKyoolKB9JVTu7gsM6E29HQvGoEZ9Us9B7KmMWPb4p00zbzVQNPr'
  stripe_publishable_key: 'pk_test_51K94u5GTOwaKvPHXCfI2Zhcrj7muSmB1cQk1Z1XP2Qs2Q4jKAIOSOoLhlWJk4D654gP5Y4Qz3zGqCagdR2T887eu003vZIXoiU'

production:
  stripe_secret_key: 'sk_test_51K94u5GTOwaKvPHXmQZk5UIuV5Ye9dYwWQymazbCvB29G7nKyoolKB9JVTu7gsM6E29HQvGoEZ9Us9B7KmMWPb4p00zbzVQNPr'
  stripe_publishable_key: 'pk_test_51K94u5GTOwaKvPHXCfI2Zhcrj7muSmB1cQk1Z1XP2Qs2Q4jKAIOSOoLhlWJk4D654gP5Y4Qz3zGqCagdR2T887eu003vZIXoiU'